language: node_js
dist: precise
node_js: "8"
script: npm run test && npm run build
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: script
  script: touch ~/.npmrc && echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> ~/.npmrc && npm run publish
  skip_cleanup: true
  on:
    tags: true
after_success: npm run codecov
